{% set name = "grpcio-health-checking" %}
{% set version = "1.50.0" %}

# TODO: this upstream pin appears to not be updated w/r/t to code generation version
{% set min_protobuf = "3.12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: cf4192245bb2d64297dd789af769616398e57e087b7fb50cd7f87c51a24a83f3
  - folder: src
    url: https://github.com/grpc/grpc/archive/v{{ version }}.tar.gz
    sha256: 76900ab068da86378395a8e125b5cc43dfae671e09ff6462ddfef18676e2165a

build:
  number: 0
  noarch: python
  script: cd dist && {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - grpcio >={{ version }}
    - protobuf >={{ min_protobuf }}
    - python >=3.5

test:
  source_files:
    # checked grpc version in run_test.py
    - dist/grpc_version.py
    # the actual tests to run under coverage
    - src/src/python/grpcio_tests/tests/health_check/
    # test imports
    - src/src/python/grpcio_tests/tests/__init__.py
    - src/src/python/grpcio_tests/tests/_loader.py
    - src/src/python/grpcio_tests/tests/_result.py
    - src/src/python/grpcio_tests/tests/_runner.py
    - src/src/python/grpcio_tests/tests/unit/__init__.py
    - src/src/python/grpcio_tests/tests/unit/framework/__init__.py
    - src/src/python/grpcio_tests/tests/unit/framework/common/__init__.py
    - src/src/python/grpcio_tests/tests/unit/framework/common/test_constants.py
    - src/src/python/grpcio_tests/tests/unit/test_common.py
    - src/src/python/grpcio_tests/tests/unit/thread_pool.py
  imports:
    - grpc_health
    - grpc_health.v1.health
  commands:
    - pip check
    - cd src/src/python/grpcio_tests
    - pytest -vv -k health_check --cov grpc_health --cov-fail-under 72
  requires:
    - pip
    - pytest-cov
    # TODO: do import tests with the minimum to assure it hasn't changed
    # - protobuf =={{ min_protobuf }}

about:
  home: https://grpc.io
  summary: Standard Health Checking Service for gRPC
  license: Apache-2.0
  license_file: dist/LICENSE
  dev_url: https://github.com/grpc/grpc/tree/master/src/python/grpcio_health_checking
  doc_url: https://grpc.github.io/grpc/python/grpc_health_checking.html

extra:
  recipe-maintainers:
    - bollwyvl
